### ISSUE TITLE
Compatible issue in global-styles setting

### ISSUE THREAD

**Issue by PitterL** [mjangir/reactron#7]
In global-styles, there set the app CSS with:
```css
  #app {
    background-color: #fafafa;
    min-height: 100%;
    min-width: 100%;
  }
```
There set the background-color with a near white color, but hard to be aware of this.
Suggest to comment it which conflicted with some UI.

Referred following issue:
https://github.com/myxvisual/react-uwp/issues/75#issue-411715353
